apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_ENDPOINT: DB_ENDPOINT_SECRET_VALUE
  DB_USERNAME: DB_USERNAME_SECRET_VALUE
  DB_PASSWORD: DB_PASSWORD_SECRET_VALUE
  DB_NAME: DB_NAME_SECRET_VALUE
---
apiVersion: v1
kind: Secret
metadata:
  name: duckdns-secret
type: Opaque
data:
  DUCKDNS_TOKEN: DUCKDNS_TOKEN_SECRET_VALUE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  spec:
    containers:
      - name: app-container
        image: pecarmoregistry.azurecr.io/app:latest
        ports:
          - containerPort: 3001
        imagePullPolicy: Always
        env:
          - name: DB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_ENDPOINT
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_NAME
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:latest
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=<your-domain>.duckdns.org
        - --provider=duckdns
        env:
        - name: DUCKDNS_TOKEN
          valueFrom:
            secretKeyRef:
              name: duckdns-secret
              key: DUCKDNS_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pecarmo.duckdns.org
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001