apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: pecarmoregistry.azurecr.io/app:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DB_ENDPOINT
              value: DB_ENDPOINT_SECRET_VALUE
            - name: DB_USERNAME
              value: DB_USERNAME_SECRET_VALUE
            - name: DB_PASSWORD
              value: DB_PASSWORD_SECRET_VALUE
            - name: DB_NAME
              value: DB_NAME_SECRET_VALUE
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 80